M48
; DRILL file {KiCad (7.0.0)} date Mon Jan 20 14:18:14 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-20T14:18:14+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X3.875Y-4.45
T2
X2.0Y-2.55
X2.0Y-2.65
X2.0Y-2.75
X2.0Y-4.05
X2.0Y-4.15
X2.0Y-4.25
X4.4Y-2.55
X4.4Y-2.65
X4.4Y-2.75
X4.4Y-4.05
X4.4Y-4.15
X4.4Y-4.25
X4.4Y-4.35
X4.4Y-4.45
T0
M30
